Authors = [
'Alligator',
'Anteater',
'Armadillo',
'Aurochs',
'Axolotl',
'Badger',
'Bat',
'Beaver',
'Buffalo',
'Camel',
'Capybara',
'Chameleon',
'Cheetah',
'Chinchilla',
'Chipmunk',
'Chupacabra',
'Cormorant',
'Coyote',
'Crow',
'Dingo',
'Dinosaur',
'Dolphin',
'Duck',
'Elephant',
'Ferret',
'Fox',
'Frog',
'Giraffe',
'Gopher',
'Grizzly',
'Hedgehog',
'Hippo',
'Hyena',
'Ibex',
'Ifrit',
'Iguana',
'Jackal',
'Jackalope',
'Kangaroo',
'Koala',
'Kraken',
'Lemur',
'Leopard',
'Liger',
'Llama',
'Manatee',
'Mink',
'Monkey',
'Moose',
'Narwhal',
'Nyan Cat', 
'Orangutan',
'Otter',
'Panda',
'Penguin',
'Platypus',
'Pumpkin',
'Python',
'Quagga',
'Rabbit',
'Raccoon',
'Rhino',
'Sheep',
'Shrew',
'Skunk',
'Slow Loris', 
'Squirrel',
'Tiger',
'Turtle',
'Walrus',
'Wolf',
'Wolverine',
'Wombat'
]


RequestTitles = [
'Acknowledging first contact ',
'Troubleshooting initial problem ',
'Requesting for sensitive information',
'Notifying about escalating the issue',
'Updating on the pending issue',
'Resolving the issue',
'Notifying about initiated refund',
'Addressing product availability',
'Notifying about scheduled website downtime ',
'Responding to product functionality request',
'Responding to password reset request',
'Sharing a knowledge base link',
'Addressing positive feedback',
'Addressing negative feedback',
'Cancelling subscription request'
]